name: Get Last.fm

on:
  schedule:
    # 5分毎に実行
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.3
      - run: | 
          deno run -A ${GITHUB_WORKSPACE}/getLastFm.ts
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USER_NAME: ${{ secrets.LASTFM_USER_NAME }}
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          NOTION_COLUMN_LIST_ID: ${{ secrets.NOTION_COLUMN_LIST_ID }}
          TZ: "Asia/Tokyo"
