name: Get Filmarks

on:
  schedule:
    # 日本時間0:00に実行
    - cron: '0 15 * * *'

  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.3
      - run: |
          deno run -A ${GITHUB_WORKSPACE}/getFilmarks.ts
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          NOTION_MOVIE_DATABASE_ID: ${{ secrets.NOTION_MOVIE_DATABASE_ID }}
          TZ: "Asia/Tokyo"
    
      